Week08/Day3/w08d3_XP/giphy_project/gifs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name = 'homepage'),
    path('homepage/', views.homepage, name = 'homepage'),
    path('category/<int:category_id>/', views.category, name = 'category'),
    path('gif/<int:gif_id>/', views.gif, name = 'gif'),
    path('add_category/', views.add_category, name = 'add_category'),
    path('add_gif/', views.add_gif, name = 'add_gif'),
]

Week08/Day3/w08d3_XP/giphy_project/giphy_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gifs.urls'))
]

Week08/Day3/w08d3_XP/giphy_project/gifs/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length = 30, unique = True)

    def __str__(self):
        return self.name


class Gif(models.Model):
    title = models.CharField(max_length = 100)
    url = models.URLField()
    uploader_name = models.CharField(max_length = 50)
    created_at = models.DateTimeField(auto_now_add = True)
    category = models.ManyToManyField(Category)

    def __str__(self):
        return f"{self.title}" 

Week08/Day3/w08d3_XP/giphy_project/gifs/forms.py
from django import forms
from .models import Category


class CategoryForm(forms.Form):
    name = forms.CharField(max_length = 30)


class GifForm(forms.Form):
    title = forms.CharField(max_length = 100)
    url = forms.URLField()
    uploader_name = forms.CharField(max_length = 50)
    category = forms.ModelMultipleChoiceField(queryset=Category.objects.all())

Week08/Day3/w08d3_XP/giphy_project/gifs/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Gif, Category
from .forms import CategoryForm, GifForm

def homepage(request):
	context = { 'gifs': Gif.objects.all(), 'categories': Category.objects.all() }
	return render(request, 'homepage.html', context)

def category(request, category_id):
	return render(request, 'category.html', { 'category': Category.objects.get(id = category_id) })

def gif(request, gif_id):
	return render(request, 'gif.html', { 'gif': Gif.objects.get(id = gif_id) })

def add_category(request):
	if request.method == 'GET':
		form = CategoryForm()
		return render(request, 'add.html', { 'form':form, 'add_type':'Category' })

	if request.method == 'POST':
		form = CategoryForm(request.POST)
		if form.is_valid():
			cat = Category.objects.create(name=form.cleaned_data['name'])
		return redirect('category', cat.id)

def add_gif(request):
	if request.method == 'GET':
		form = GifForm()
		return render(request, 'add.html', { 'form':form, 'add_type':'Gif' })

	if request.method == 'POST':
		form = GifForm(request.POST)
		if form.is_valid():
			gif = Gif.objects.create(title = form.cleaned_data['title'], url = form.cleaned_data['url'], uploader_name = form.cleaned_data['uploader_name'])
			gif.category.set(form.cleaned_data['category'])
		return redirect('gif', gif.id)

Week08/Day3/w08d3_XP/giphy_project/gifs/templates/add.html
{% extends 'base.html' %} 

{% block title%}
    Add {{ add_type }} 
{% endblock %} 

{% block content %}

    <h1>Add {{ add_type }}</h1>

    <form method='post'>
        {% csrf_token %} 
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>

{% endblock %}

Week08/Day3/w08d3_XP/giphy_project/gifs/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gif Farm - {% block title%}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <style type="text/css">.main{padding: 1em;}</style>
</head>

<body>

    {% include 'partials/_navbar.html' %}
    <div class = "main">
        {% block content%} 
        {% endblock %}
    </div>

</body>

</html>

Week08/Day3/w08d3_XP/giphy_project/gifs/templates/category.html
{% extends 'base.html' %} 

{% block title%}
Category - {{ category.name }}
{% endblock %} 

{% block content %}

    <h1>Gifs attached to Category: {{ category.name }}</h1> 

    <div class = "row">
        {% for gif in category.gif_set.all %}
            <div class = "col-md-2">
                <a href = "{% url 'gif' gif.id  %}" class = "thumbnail">
                    <img src = '{{gif.url}}' class = "img-thumbnail" alt='{{ gif.title }}'>
                </a>
            </div>
        {% endfor %}
    </div>

{% endblock %}

Week08/Day3/w08d3_XP/giphy_project/gifs/templates/gif.html
{% extends 'base.html' %} 

{% block title%}Details for Gif {{gif.id}}{% endblock %} 

{% block content %}

    <h1>Details for Gif {{gif.id}}</h1>

    <ul>
        <li>Title: {{ gif.title }}</li>
        <li>Uploader: {{ gif.uploader_name }}</li>
        <li>Creation: {{ gif.created_at }}</li>
    </ul>
    <img src='{{gif.url}}' class="img-thumbnail" alt='{{ gif.title }}'>
    <hr>
    <h6>This gif is attached to the following categories:</h6>
    <div>
        {% for cat in gif.category.all %}
            <a href = "{% url 'category' cat.id  %}" class = "thumbnail">
                <button type="button" class="btn btn-sm btn-primary">{{cat.name}}</button>
            </a>
        {%  endfor %}
    </div>

{% endblock %}

Week08/Day3/w08d3_XP/giphy_project/gifs/templates/homepage.html
{% extends 'base.html' %}

{% block title %}All gifs{% endblock %}

{% block content%}
    <h3>All categories</h3>
    <div>
    {% for cat in categories %}
        <a href = "{% url 'category' cat.id  %}" class = "thumbnail">
            <button type="button" class="btn btn-sm btn-primary">{{cat.name}}</button>
        </a>
    {%  endfor %}
    </div>
    <hr>
    <h3>All gifs</h3>

    <div class = "row">
    {% for gif in gifs %}
        <div class = "col-md-2">
            <a href = "#" class = "thumbnail">
            <img src = '{{gif.url}}' class = "img-thumbnail" alt='{{ gif.title }}'>
            </a>
        </div>
    {% endfor %}
    </div>

{% endblock %}

Week08/Day3/w08d3_XP/giphy_project/gifs/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage' %}">GIFS Farm</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_category' %}">Add Category</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_gif' %}">Add Gif</a>
                </li>
            </ul>

        </div>
    </div>
</nav>